#!/bin/zsh

usage() {
    >&2 echo "Usage: $0 <source> <target>"
}

source=$1
target=$2

if [[ -z "$source" ]] || [[ -z "$target" ]]; then
    usage
    exit 1
fi

if ! [[ -f "$source" ]]; then
    >&2 echo "Error: Expected source to be a file"
    usage
    exit 1
fi

while : ; do
    source_content="$(cat "$source")"
    target_content="$(cat "$target" || "")"
    if [[ "$source_content" != "$target_content" ]]; then
        tput setaf 3
        echo "File change. Synchronizing..."
        tput sgr0
        cp "$source" "$target"
        tput setaf 2
        echo "File synchronized!"
        tput sgr0
    fi
    sleep 0.1
done
